import React, { useEffect, useState } from 'react';
import { Search } from 'lucide-react';
import api from '../../api/axios';

const Certificates = () => {
  const [certificates, setCertificates] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');

  useEffect(() => {
    fetchCertificates();
  }, []);

  const fetchCertificates = async () => {
    try {
      const res = await api.get('/certificates');
      setCertificates(res.data.data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const filtered = certificates.filter(c => 
     c.student_name.toLowerCase().includes(searchTerm.toLowerCase()) || 
     c.event_title.toLowerCase().includes(searchTerm.toLowerCase())
  );

  if (loading) return <div className="flex justify-center p-12"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-accent-blue"></div></div>;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold">Certificates Log</h1>
        <p className="text-text-muted mt-1">Audit log of all securely issued certificates generated by system triggers.</p>
      </div>

      <div className="glass-panel rounded-xl overflow-hidden p-6 flex justify-between items-center gap-4">
         <div className="relative w-full md:w-96">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-text-muted" size={18} />
            <input 
               type="text" 
               placeholder="Search by student or event..." 
               value={searchTerm}
               onChange={(e) => setSearchTerm(e.target.value)}
               className="w-full bg-glass-bg border border-glass-border rounded-lg pl-10 pr-4 py-2 focus:outline-none focus:ring-2 focus:ring-accent-blue/50 text-text-primary placeholder:text-text-muted"
            />
         </div>
      </div>

      <div className="glass-panel rounded-xl overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-glass-bg border-b border-glass-border">
                <th className="py-4 px-6 font-semibold text-text-muted">Cert ID</th>
                <th className="py-4 px-6 font-semibold text-text-muted">Student</th>
                <th className="py-4 px-6 font-semibold text-text-muted">Event Title</th>
                <th className="py-4 px-6 font-semibold text-text-muted">Issue Date</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-glass-border">
              {filtered.map((cert) => (
                  <tr key={cert.cert_id} className="hover:bg-glass-bg/50 transition-colors">
                    <td className="py-4 px-6">
                       <span className="font-mono text-sm text-accent-gold bg-accent-gold/10 px-2 py-1 rounded border border-accent-gold/20">
                          CERT-{cert.cert_id.toString().padStart(4, '0')}
                       </span>
                    </td>
                    <td className="py-4 px-6">
                       <div className="font-medium">{cert.student_name}</div>
                       <div className="text-text-muted text-sm">{cert.department}</div>
                    </td>
                    <td className="py-4 px-6 text-text-muted">{cert.event_title}</td>
                    <td className="py-4 px-6 text-text-muted">{new Date(cert.issue_date).toLocaleString()}</td>
                  </tr>
                ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default Certificates;
